# Generated by Django 5.2.3 on 2025-06-29 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttransportdetail',
            name='route',
        ),
        migrations.AddField(
            model_name='studenttransportdetail',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.vehicle'),
        ),
        migrations.AlterField(
            model_name='studenttransportdetail',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.routepickuppoint'),
        ),
    ]
