# Generated by Django 5.2.3 on 2025-06-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_studenttransportdetail_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='fees_total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
